pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
  build:
    image: node:9.11
    commands:
      - npm install
      - npm run pack-all
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
  artifactory:
    image: athieriot/drone-artifactory
    environment:
      - DRONE_VERSION=0.8
    group_id: tech.brewlabs
    artifact_id: tech.brewlabs.blang
    version: 0.1.0-SNAPSHOT
    files:
      - package/*tar.gz
    force_upload: true
    secrets: [ artifactory_url, artifactory_username, artifactory_password ]
    when:
      branch: master
      status: [ success ]
  slack:
    image: plugins/slack
    channel: cados-builds
    secrets: [ slack_webhook ]
    when:
      branch: master
      status: [ success, failure ]
